DROP TABLE starwarsdb.PLANET;

CREATE TABLE starwarsdb.PLANET (
	PLANET_UID INT(10) NOT NULL AUTO_INCREMENT,
	NAME 		VARCHAR(50) NOT NULL,
	WEATHER 	VARCHAR(50) NOT NULL,
	TERRAIN 	VARCHAR(50) NOT NULL,
	NUM_FILMS 	INT(10) NOT NULL,
	CONSTRAINT PLANET_PK PRIMARY KEY (PLANET_UID)
);
